# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2eddc52a2ffaa14845d732b46cf9ae2e190a7d8c98c3723aa644071703b00ae82e580d613f0c4507883f1d5732caa5a02b2b376995b35d4256dbdfe9da7261af

test:
  secret_key_base: 84474e585bf67dc436a6e3ea321a53212b6e1e72d24210801959dda8cbe286ee59802f56208a4e9510394a1f432874be924056d626d485efb3ecadab5520fe52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
